export default [
    {
        _id: "1",
        quizId: "1000",
        questionType: "Multiple Choice",
        title: "Question 1",
        points: 1,
        content: "What number was the Apollo mission that successfully put a man on the moon for the first time in human history?",
        answer: ["Apollo 11"],
        options: ["Apollo 11", "Apollo 12", "Apollo 13"],
        numOptions: 3,
    },

    {
        _id: "2",
        quizId: "1000",
        questionType: "True/False",
        title: "Question 2",
        points: 1,
        content: "The earth is flat",
        answer: ["False"],
        options: ["True", "False"],
        numOptions: 2,
    },
    {
        _id: "3",
        quizId: "1000",
        questionType: "Blank",
        title: "Question 3",
        points: 1,
        content: "What city is your school in?",
        answer: ["Boston"],
        options: [],
        numOptions: 3,
    },
    {
        _id: "4",
        quizId: "1001",
        questionType: "Multiple Choice",
        title: "Question 1",
        points: 1,
        content: "Which of the following is NOT a fruit?",
        answer: ["Rhubarb"],
        options: ["Tomatoes", "Avocados", "Rhubarb", "Apple"],
        numOptions: 4,
    },
    {
        _id: "5",
        quizId: "1001",
        questionType: "True/False",
        title: "Question 2",
        points: 1,
        content: "China is in Asia",
        answer: ["True"],
        options: ["True", "False"],
        numOptions: 2,
    },
    {
        _id: "6",
        quizId: "1001",
        questionType: "Blank",
        title: "Question 3",
        points: 1,
        content: "What does JSON stand for",
        answer: ["JavaScript", "Script", "Object", "Notation"],
        options: [],
        numOptions: 4,
    },
    {
        _id: "7",
        quizId: "1002",
        questionType: "Multiple Choice",
        title: "Question 1",
        points: 1,
        content: "What number was the Apollo mission that successfully put a man on the moon for the first time in human history?",
        answer: ["Apollo 11"],
        options: ["Apollo 11", "Apollo 12", "Apollo 13"],
        numOptions: 3,
    },
    {
        _id: "8",
        quizId: "1002",
        questionType: "True/False",
        title: "Question 2",
        points: 1,
        content: "Earth is a planet",
        answer: ["True"],
        options: ["True", "False"],
        numOptions: 2,
    },
    {
        _id: "9",
        quizId: "1002",
        questionType: "Blank",
        title: "Question 3",
        points: 1,
        content: "What state is your school in?",
        answer: ["Massachussets"],
        options: [],
        numOptions: 3,
    },

];