export default [
    {
      _id: "1000",
      title: "Syllabus Quiz",
      course: "RS101",
      description: "Making sure students understand the course syllabus",
      quizType: "Graded Quiz",
      points: 100,
      assignmentGroup: "Quizzes",
      shuffleAnswers: true,
      timeLimit: 20,
      multipleAttempts: false,
      showCorrectAnswers: false,
      accessCode: "",
      oneQuestionAtATime: true,
      webcamRequired: false,
      lockQuestionsAfterAnswering: false,
      dueDate: "2024-01-11",
      availableDate: "2024-01-10",
      untilDate: "2024-01-11",
    },
    {
        _id: "1001",
        title: "Quiz 1 - Intro to Course",
        course: "RS102",
        description: "Testing Chapter 1",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11",
        availableDate: "2024-01-17",
        untilDate: "2024-01-21",
    },
    {
        _id: "1002",
        title: "Quiz 1 - Intro to Course",
        course: "RS101",
        description: "Starting off the semester strong",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11",
        availableDate: "2024-01-22",
        untilDate: "2024-01-25",
    },
    {
        _id: "1003",
        title: "Quiz 2 - Electricity and Magnetism",
        course: "RS101",
        description: "Chapter 2 Foundations",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11",
        availableDate: "2024-01-27",
        untilDate: "2024-01-31",
    },
  ];