export default [
    {
        _id: "1000",
        title: "Syllabus Quiz",
        course: "RS101",
        description: "Making sure students understand the course syllabus",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11T23:59:59",
        availableDate: "2024-01-10T23:59:59",
        untilDate: "2024-01-11T23:59:59",
        published: false,
        viewResponses: "Always",
        lockdownRequired: true,
        viewQuizResults: true,
        for: "Everyone",
    },
    {
        _id: "1001",
        title: "Quiz 1 - Intro to Course",
        course: "RS102",
        description: "Testing Chapter 1",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11T23:59:59",
        availableDate: "2024-01-17T23:59:59",
        untilDate: "2024-01-21T23:59:59",
        published: false,
    },
    {
        _id: "1002",
        title: "Quiz 1 - Intro to Course",
        course: "RS101",
        description: "Starting off the semester strong",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11T23:59:59",
        availableDate: "2024-01-22T23:59:59",
        untilDate: "2024-01-25T23:59:59",
        published: false,
    },
    {
        _id: "1003",
        title: "Quiz 2 - Electricity and Magnetism",
        course: "RS101",
        description: "Chapter 2 Foundations",
        quizType: "Graded Quiz",
        points: 100,
        assignmentGroup: "Quizzes",
        shuffleAnswers: true,
        timeLimit: 20,
        multipleAttempts: false,
        showCorrectAnswers: false,
        accessCode: "",
        oneQuestionAtATime: true,
        webcamRequired: false,
        lockQuestionsAfterAnswering: false,
        dueDate: "2024-01-11T23:59:59",
        availableDate: "2024-01-27T23:59:59",
        untilDate: "2024-01-31T23:59:59",
        published: false,
    },
];